### ISSUE TITLE
@modulus/standard not available for certain versions of node

### ISSUE THREAD

**Issue by theworkflow** [onmodulus/standard#2]
I've tried to install @modulus/standard for testing but it doesn't seem that it's available for versions of nodev 0.10.40, npm v1.3.28 and below. Is there a minimal version of node/npm that it has to be used to install this module?

Node Version: 0.10.40
NPM Version: 1.4.28

**Comment by fiveisprime** [comment]
Yes, scoped modules require npm@>2.7.0; node 0.10.x is fine, just your npm needs updated. :+1:
