### ISSUE TITLE
Print warnings even if no errors exists

### ISSUE THREAD

**Issue by jackboberg** [onmodulus/standard#3]
Currently if the code you are testing includes warnings, but not errors, nothing is printed to `stdout`. We should print these warnings and exit with a status code of `0`.

We may need to fork `standard-engine` in order to make this feature work as described.

**Comment by tzmanics** [comment]
yes, yes, yes!

**Comment by jackboberg** [comment]
Resolved with [`standard-engine@2.2.4`](https://github.com/Flet/standard-engine/commit/5613b98b61cfd2374b1beaf3b2c9130e63f2f512)
